ALTER TABLE medicos ADD COLUMN status BOOLEAN DEFAULT TRUE;
UPDATE medicos SET status = TRUE;
ALTER TABLE medicos ALTER COLUMN status SET NOT NULL;
ALTER TABLE medicos ALTER COLUMN status SET DEFAULT TRUE;